import type { RealizedYieldEntry, Seam } from "../src/index.js";

export const FIXTURE_NOW = "2026-08-15T00:00:00.000Z";

/** Reference price used across the fixtures, so USD-denominated ceilings are checkable. */
export const BTC_PRICE_USD = 100_000;

/** Synthetic seam builder for focused unit tests. Defaults are deliberately benign. */
export function seam(overrides: Partial<Seam> & Pick<Seam, "id">): Seam {
  return {
    name: overrides.id,
    venue: "venue-a",
    asset: "cbBTC",
    assetMint: `mint-${overrides.id}`,
    kind: "lending",
    yieldKind: "sustainable",
    apyBps: 400,
    apy7dBps: 400,
    apy30dBps: 400,
    apy90dMedianBps: null,
    tvlUsd: 50_000_000,
    allocationBps: 0,
    emissionToken: null,
    emissionEndsAt: null,
    riskTier: "low",
    belowLiquidityFloor: false,
    sourceDivergence: false,
    ilEstimateBps: null,
    pairVolatilityClass: null,
    wrapHops: 1,
    sourceUrl: "https://lodz.money/seam",
    updatedAt: FIXTURE_NOW,
    ...overrides,
  };
}

/**
 * The measured Solana BTC seam table, transcribed from
 * `docs/research/btc-on-solana.md` sections 2 and 7 (snapshot 2026-08-15).
 *
 * Percentages are converted to basis points and rounded to the nearest whole basis
 * point. Fields the research did not measure are `null` rather than filled in:
 *
 * - `ilEstimateBps` is null on every LP seam because DefiLlama reports `il7d` as null
 *   for all of them and nobody has computed it independently yet. Null means unmeasured,
 *   not zero.
 * - `apy7dBps` / `apy30dBps` / `apy90dMedianBps` are null where the research table shows
 *   no figure for that window.
 * - Risk tiers follow the asset trust models in research section 6-1: WBTC is bridged
 *   through Portal, the bridge exploited for 326 million dollars in 2022, so WBTC-backed
 *   seams are tiered high. Assigning tiers is the risk layer's job, not this package's;
 *   these are the fixture's stated assumption.
 * - X1's deposit asset and hop count are an assumption. GMTrade publishes no API, so the
 *   research marks its internals unverified. Treated here as a USDC-denominated vault
 *   with no wrapped BTC in the custody path.
 */
export const MEASURED_SEAMS: Seam[] = [
  {
    id: "S1",
    name: "Orca SOL-cbBTC",
    venue: "Orca",
    asset: "cbBTC",
    assetMint: "cbbtcf3aa214zXHbiAZQwf4122FBYbraNdFqgw4iMij",
    kind: "lp",
    yieldKind: "sustainable",
    apyBps: 1_605,
    apy7dBps: 2_191,
    apy30dBps: 2_415,
    apy90dMedianBps: null,
    tvlUsd: 4_582_272,
    allocationBps: 0,
    emissionToken: null,
    emissionEndsAt: null,
    riskTier: "medium",
    belowLiquidityFloor: false,
    sourceDivergence: false,
    ilEstimateBps: null,
    pairVolatilityClass: "uncorrelated",
    wrapHops: 1,
    sourceUrl: "https://yields.llama.fi/chart/6dc30ef3-d497-497c-91f3-b4ccb817a8b9",
    updatedAt: FIXTURE_NOW,
  },
  {
    id: "S2",
    name: "Orca cbBTC-USDC",
    venue: "Orca",
    asset: "cbBTC",
    assetMint: "cbbtcf3aa214zXHbiAZQwf4122FBYbraNdFqgw4iMij",
    kind: "lp",
    yieldKind: "sustainable",
    apyBps: 1_500,
    apy7dBps: 1_546,
    apy30dBps: 2_201,
    apy90dMedianBps: 2_850,
    tvlUsd: 6_319_470,
    allocationBps: 0,
    emissionToken: null,
    emissionEndsAt: null,
    riskTier: "medium",
    belowLiquidityFloor: false,
    sourceDivergence: false,
    ilEstimateBps: null,
    pairVolatilityClass: "uncorrelated",
    wrapHops: 1,
    sourceUrl: "https://yields.llama.fi/chart/2651188f-6b05-473e-9cfb-977a4ad094ba",
    updatedAt: FIXTURE_NOW,
  },
  {
    id: "S3",
    name: "Orca SOL-WBTC",
    venue: "Orca",
    asset: "WBTC",
    assetMint: "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh",
    kind: "lp",
    yieldKind: "sustainable",
    apyBps: 743,
    apy7dBps: 1_101,
    apy30dBps: 1_041,
    apy90dMedianBps: null,
    tvlUsd: 929_760,
    allocationBps: 0,
    emissionToken: null,
    emissionEndsAt: null,
    riskTier: "high",
    belowLiquidityFloor: false,
    sourceDivergence: false,
    ilEstimateBps: null,
    pairVolatilityClass: "uncorrelated",
    wrapHops: 2,
    sourceUrl: "https://yields.llama.fi/chart/ab47588f-831d-489b-9520-095663bbea59",
    updatedAt: FIXTURE_NOW,
  },
  {
    id: "S4",
    name: "Orca cbBTC-WBTC",
    venue: "Orca",
    asset: "WBTC",
    assetMint: "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh",
    kind: "lp",
    yieldKind: "sustainable",
    apyBps: 596,
    apy7dBps: 435,
    apy30dBps: 347,
    apy90dMedianBps: null,
    tvlUsd: 1_011_417,
    allocationBps: 0,
    emissionToken: null,
    emissionEndsAt: null,
    riskTier: "high",
    belowLiquidityFloor: false,
    sourceDivergence: false,
    ilEstimateBps: null,
    pairVolatilityClass: "correlated",
    wrapHops: 2,
    sourceUrl: "https://yields.llama.fi/chart/42dc3364-dd6b-47e7-a2e3-f4907bb3b5d2",
    updatedAt: FIXTURE_NOW,
  },
  {
    id: "S5",
    name: "Orca cbBTC-JLP",
    venue: "Orca",
    asset: "cbBTC",
    assetMint: "cbbtcf3aa214zXHbiAZQwf4122FBYbraNdFqgw4iMij",
    kind: "lp",
    yieldKind: "sustainable",
    apyBps: 475,
    apy7dBps: 667,
    apy30dBps: 441,
    apy90dMedianBps: null,
    tvlUsd: 213_737,
    allocationBps: 0,
    emissionToken: null,
    emissionEndsAt: null,
    riskTier: "high",
    belowLiquidityFloor: false,
    sourceDivergence: false,
    ilEstimateBps: null,
    pairVolatilityClass: "mixed",
    wrapHops: 1,
    sourceUrl: "https://yields.llama.fi/chart/793745f5-f320-416e-9c86-53a5d4e02c99",
    updatedAt: FIXTURE_NOW,
  },
  {
    id: "S6",
    name: "Orca WBTC-USDC",
    venue: "Orca",
    asset: "WBTC",
    assetMint: "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh",
    kind: "lp",
    yieldKind: "sustainable",
    apyBps: 230,
    apy7dBps: 467,
    apy30dBps: null,
    apy90dMedianBps: null,
    tvlUsd: 106_440,
    allocationBps: 0,
    emissionToken: null,
    emissionEndsAt: null,
    riskTier: "high",
    belowLiquidityFloor: false,
    sourceDivergence: false,
    ilEstimateBps: null,
    pairVolatilityClass: "uncorrelated",
    wrapHops: 2,
    sourceUrl: "https://yields.llama.fi/chart/409066bb-22eb-4c9e-994f-dfcea35e4481",
    updatedAt: FIXTURE_NOW,
  },
  {
    id: "S7",
    name: "Orca USDG-xBTC",
    venue: "Orca",
    asset: "xBTC",
    assetMint: "xBTC-mint",
    kind: "lp",
    yieldKind: "sustainable",
    apyBps: 138,
    apy7dBps: 154,
    apy30dBps: 242,
    apy90dMedianBps: null,
    tvlUsd: 2_010_937,
    allocationBps: 0,
    emissionToken: null,
    emissionEndsAt: null,
    riskTier: "medium",
    belowLiquidityFloor: false,
    sourceDivergence: false,
    ilEstimateBps: null,
    pairVolatilityClass: "uncorrelated",
    wrapHops: 1,
    sourceUrl: "https://yields.llama.fi/chart/a342ad05-4072-4571-9b37-7f5685a80f8a",
    updatedAt: FIXTURE_NOW,
  },
  {
    id: "S8",
    name: "Kamino Liquidity USDG-xBTC",
    venue: "Kamino Liquidity",
    asset: "xBTC",
    assetMint: "xBTC-mint",
    kind: "lp",
    yieldKind: "sustainable",
    apyBps: 119,
    apy7dBps: 123,
    apy30dBps: null,
    apy90dMedianBps: null,
    tvlUsd: 2_011_421,
    allocationBps: 0,
    emissionToken: null,
    emissionEndsAt: null,
    riskTier: "medium",
    belowLiquidityFloor: false,
    sourceDivergence: false,
    ilEstimateBps: null,
    pairVolatilityClass: "uncorrelated",
    wrapHops: 1,
    sourceUrl: "https://yields.llama.fi/chart/6e8b600a-aa3b-402d-a68a-7dec1a097585",
    updatedAt: FIXTURE_NOW,
  },
  {
    id: "S9",
    name: "Loopscale zBTC lending",
    venue: "Loopscale",
    asset: "zBTC",
    assetMint: "zBTC-mint",
    kind: "lending",
    yieldKind: "sustainable",
    apyBps: 106,
    apy7dBps: null,
    apy30dBps: 86,
    apy90dMedianBps: null,
    tvlUsd: 294_950,
    allocationBps: 0,
    emissionToken: null,
    emissionEndsAt: null,
    riskTier: "medium",
    belowLiquidityFloor: false,
    sourceDivergence: false,
    ilEstimateBps: null,
    pairVolatilityClass: null,
    wrapHops: 1,
    sourceUrl: "https://yields.llama.fi/chart/8544e9ed-02b3-4374-84b6-9d0bd380c1c5",
    updatedAt: FIXTURE_NOW,
  },
  {
    id: "S10",
    name: "Orca cbBTC-xBTC",
    venue: "Orca",
    asset: "xBTC",
    assetMint: "xBTC-mint",
    kind: "lp",
    yieldKind: "sustainable",
    apyBps: 99,
    apy7dBps: 80,
    apy30dBps: null,
    apy90dMedianBps: null,
    tvlUsd: 277_528,
    allocationBps: 0,
    emissionToken: null,
    emissionEndsAt: null,
    riskTier: "medium",
    belowLiquidityFloor: false,
    sourceDivergence: false,
    ilEstimateBps: null,
    pairVolatilityClass: "correlated",
    wrapHops: 1,
    sourceUrl: "https://yields.llama.fi/chart/5da5ddfa-7b18-4b3c-bb01-380174cbf449",
    updatedAt: FIXTURE_NOW,
  },
  {
    id: "S11",
    name: "Save cbBTC lending",
    venue: "Save",
    asset: "cbBTC",
    assetMint: "cbbtcf3aa214zXHbiAZQwf4122FBYbraNdFqgw4iMij",
    kind: "lending",
    yieldKind: "sustainable",
    apyBps: 19,
    apy7dBps: null,
    apy30dBps: 18,
    apy90dMedianBps: null,
    tvlUsd: 1_786_910,
    allocationBps: 0,
    emissionToken: null,
    emissionEndsAt: null,
    riskTier: "low",
    belowLiquidityFloor: false,
    sourceDivergence: false,
    ilEstimateBps: null,
    pairVolatilityClass: null,
    wrapHops: 1,
    sourceUrl: "https://api.solend.fi/v1/reserves?scope=all",
    updatedAt: FIXTURE_NOW,
  },
  {
    id: "S12",
    name: "Kamino Lend cbBTC",
    venue: "Kamino Lend",
    asset: "cbBTC",
    assetMint: "cbbtcf3aa214zXHbiAZQwf4122FBYbraNdFqgw4iMij",
    kind: "lending",
    yieldKind: "sustainable",
    apyBps: 0,
    apy7dBps: null,
    apy30dBps: 2,
    apy90dMedianBps: null,
    tvlUsd: 44_039_651,
    allocationBps: 0,
    emissionToken: null,
    emissionEndsAt: null,
    riskTier: "low",
    belowLiquidityFloor: false,
    sourceDivergence: false,
    ilEstimateBps: null,
    pairVolatilityClass: null,
    wrapHops: 1,
    sourceUrl: "https://api.kamino.finance/kamino-market/7u3HeHxYDLhnCoErrtycNokbQYbWGzLs6JSDqGAv5PfF/reserves/metrics",
    updatedAt: FIXTURE_NOW,
  },
  {
    id: "S13",
    name: "Kamino Lend xBTC",
    venue: "Kamino Lend",
    asset: "xBTC",
    assetMint: "xBTC-mint",
    kind: "lending",
    yieldKind: "sustainable",
    apyBps: 0,
    apy7dBps: null,
    apy30dBps: 1,
    apy90dMedianBps: null,
    tvlUsd: 13_586_700,
    allocationBps: 0,
    emissionToken: null,
    emissionEndsAt: null,
    riskTier: "low",
    belowLiquidityFloor: false,
    sourceDivergence: false,
    ilEstimateBps: null,
    pairVolatilityClass: null,
    wrapHops: 1,
    sourceUrl: "https://api.kamino.finance/kamino-market/7u3HeHxYDLhnCoErrtycNokbQYbWGzLs6JSDqGAv5PfF/reserves/metrics",
    updatedAt: FIXTURE_NOW,
  },
  {
    id: "S14",
    name: "Kamino Lend WBTC",
    venue: "Kamino Lend",
    asset: "WBTC",
    assetMint: "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh",
    kind: "lending",
    yieldKind: "sustainable",
    apyBps: 2,
    apy7dBps: null,
    apy30dBps: null,
    apy90dMedianBps: null,
    tvlUsd: 153_429,
    allocationBps: 0,
    emissionToken: null,
    emissionEndsAt: null,
    riskTier: "high",
    belowLiquidityFloor: false,
    sourceDivergence: false,
    ilEstimateBps: null,
    pairVolatilityClass: null,
    wrapHops: 2,
    sourceUrl: "https://api.kamino.finance/kamino-market/7u3HeHxYDLhnCoErrtycNokbQYbWGzLs6JSDqGAv5PfF/reserves/metrics",
    updatedAt: FIXTURE_NOW,
  },
  {
    id: "S15",
    name: "Jupiter Lend cbBTC",
    venue: "Jupiter Lend",
    asset: "cbBTC",
    assetMint: "cbbtcf3aa214zXHbiAZQwf4122FBYbraNdFqgw4iMij",
    kind: "lending",
    yieldKind: "sustainable",
    apyBps: 0,
    apy7dBps: null,
    apy30dBps: 0,
    apy90dMedianBps: null,
    tvlUsd: 6_231_807,
    allocationBps: 0,
    emissionToken: null,
    emissionEndsAt: null,
    riskTier: "low",
    belowLiquidityFloor: false,
    sourceDivergence: false,
    ilEstimateBps: null,
    pairVolatilityClass: null,
    wrapHops: 1,
    sourceUrl: "https://yields.llama.fi/pools",
    updatedAt: FIXTURE_NOW,
  },
  {
    id: "X1",
    name: "GMTrade BTC-USDC vault",
    venue: "GMTrade",
    asset: "USDC",
    assetMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    kind: "basis",
    yieldKind: "counterparty",
    apyBps: 21_483,
    apy7dBps: null,
    apy30dBps: 17_446,
    apy90dMedianBps: null,
    tvlUsd: 1_709_236,
    allocationBps: 0,
    emissionToken: null,
    emissionEndsAt: null,
    riskTier: "high",
    belowLiquidityFloor: false,
    sourceDivergence: false,
    ilEstimateBps: null,
    pairVolatilityClass: null,
    wrapHops: 0,
    sourceUrl: "https://yields.llama.fi/chart/3e6c799e-d07e-45f5-9854-9f0c18fe7646",
    updatedAt: FIXTURE_NOW,
  },
  {
    id: "Z1",
    name: "Kamino Zeus Bitcoin Market USDC",
    venue: "Kamino Lend",
    asset: "USDC",
    assetMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    kind: "lending",
    yieldKind: "sustainable",
    apyBps: 10_462,
    apy7dBps: null,
    apy30dBps: null,
    apy90dMedianBps: null,
    tvlUsd: 10_927,
    allocationBps: 0,
    emissionToken: null,
    emissionEndsAt: null,
    riskTier: "high",
    belowLiquidityFloor: true,
    sourceDivergence: false,
    ilEstimateBps: null,
    pairVolatilityClass: null,
    wrapHops: 0,
    sourceUrl: "https://api.kamino.finance/kamino-market/E6Tq3XV4Dgqx1QwEUT1u4goM7794sPmb1cGvr7V4Xf6J/reserves/metrics",
    updatedAt: FIXTURE_NOW,
  },
];

/**
 * The documented spot artifact: Orca cbBTC-USDC had a day in its 646 day history
 * reading 74,187 percent apyBase, produced by a normal fee take divided by a
 * momentarily tiny TVL.
 */
export const SPOT_SPIKE_BPS = 7_418_700;

export const REALIZED_ENTRIES: RealizedYieldEntry[] = [
  { seamId: "S2", venue: "Orca", asset: "cbBTC", yieldKind: "sustainable", amountBtc: 0.042, token: "cbBTC", at: "2026-07-05T00:00:00.000Z" },
  { seamId: "S1", venue: "Orca", asset: "cbBTC", yieldKind: "sustainable", amountBtc: 0.031, token: "cbBTC", at: "2026-07-12T00:00:00.000Z" },
  { seamId: "S9", venue: "Loopscale", asset: "zBTC", yieldKind: "sustainable", amountBtc: 0.058, token: "zBTC", at: "2026-07-19T00:00:00.000Z" },
  { seamId: "X1", venue: "GMTrade", asset: "USDC", yieldKind: "counterparty", amountBtc: 0.076, token: "USDC", at: "2026-07-26T00:00:00.000Z" },
  { seamId: "X1", venue: "GMTrade", asset: "USDC", yieldKind: "counterparty", amountBtc: 0.049, token: "USDC", at: "2026-08-02T00:00:00.000Z" },
  { seamId: "S1", venue: "Orca", asset: "cbBTC", yieldKind: "emissions", amountBtc: 0.011, token: "emission-token-a", at: "2026-08-09T00:00:00.000Z" },
];

/**
 * Deterministic pseudo-random source for property tests. A linear congruential
 * generator is used instead of Math.random so a failing case can always be reproduced
 * from its seed.
 */
export function makeRandom(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    return state / 4_294_967_296;
  };
}
